### ISSUE TITLE
Is the training / validation / test datasets publicly available?

### ISSUE THREAD

**Issue by ostrokach** [eternagame/EternaBrain#38]
I was wondering if the training, validation, and test datasets for EternaBrain were publicly available? In particular, I am looking for a dataset of RNA sequences and contact maps. I don't really need the specific player moves.

Thank you for your help, and sorry if this is off topic.

**Comment by RK900** [comment]
Sorry about the (super) late reply, but the files were too big to be uploaded to GitHub. They might be downloadable from software.eternagame.org.
